//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace Effort.Test.Data.Feature
{
    public class FeatureObjectContext : ObjectContext, IDisposable
    {
        public const string ContainerName = "FeatureObjectContext";
    
    	public const string DefaultConnectionString = "name=FeatureObjectContext";
    
        #region Constructors
    
        public FeatureObjectContext(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public FeatureObjectContext(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<TimestampSupport> TimestampSupports
        {
            get { return _timestampSupports  ?? (_timestampSupports = CreateObjectSet<TimestampSupport>("TimestampSupports")); }
        }
        private ObjectSet<TimestampSupport> _timestampSupports;

        #endregion
    
    }
}
