//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Effort.Test.Data.Feature
{
    
    public class ForeignEntity
    {
        public virtual int ID { get; set; }
    
        public virtual int FID1 { get; set; }
    
        public virtual int FID2 { get; set; }
    
        public virtual string ForeignData { get; set; }
    
        public virtual PrimaryEntity PrimaryEntity { get; set; }
    
    
    }
}
