//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Effort.Test.Data.Northwind
{
    
    public class Order
    {
        public virtual int OrderID { get; set; }
    
        public virtual string CustomerID { get; set; }
    
        public virtual Nullable<int> EmployeeID { get; set; }
    
        public virtual Nullable<System.DateTime> OrderDate { get; set; }
    
        public virtual Nullable<System.DateTime> RequiredDate { get; set; }
    
        public virtual Nullable<System.DateTime> ShippedDate { get; set; }
    
        public virtual Nullable<int> ShipVia { get; set; }
    
        public virtual Nullable<decimal> Freight { get; set; }
    
        public virtual string ShipName { get; set; }
    
        public virtual string ShipAddress { get; set; }
    
        public virtual string ShipCity { get; set; }
    
        public virtual string ShipRegion { get; set; }
    
        public virtual string ShipPostalCode { get; set; }
    
        public virtual string ShipCountry { get; set; }
    
        public virtual Customer Customer { get; set; }
    
        public virtual Employee Employee { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    
        public virtual Shipper Shipper { get; set; }
    
    
    }
}
