//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Effort.Example.Models
{
    public partial class Product
    {
        #region Primitive Properties
    
        public virtual int ProductID
        {
            get;
            set;
        }
    
        public virtual string ProductName
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SupplierID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CategoryID
        {
            get { return _categoryID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_categoryID != value)
                    {
                        if (Categories != null && Categories.CategoryID != value)
                        {
                            Categories = null;
                        }
                        _categoryID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _categoryID;
    
        public virtual string QuantityPerUnit
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> UnitPrice
        {
            get;
            set;
        }
    
        public virtual Nullable<short> UnitsInStock
        {
            get;
            set;
        }
    
        public virtual Nullable<short> UnitsOnOrder
        {
            get;
            set;
        }
    
        public virtual Nullable<short> ReorderLevel
        {
            get;
            set;
        }
    
        public virtual bool Discontinued
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Category Categories
        {
            get { return _categories; }
            set
            {
                if (!ReferenceEquals(_categories, value))
                {
                    var previousValue = _categories;
                    _categories = value;
                    FixupCategories(previousValue);
                }
            }
        }
        private Category _categories;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupCategories(Category previousValue)
        {
            if (previousValue != null && previousValue.Products.Contains(this))
            {
                previousValue.Products.Remove(this);
            }
    
            if (Categories != null)
            {
                if (!Categories.Products.Contains(this))
                {
                    Categories.Products.Add(this);
                }
                if (CategoryID != Categories.CategoryID)
                {
                    CategoryID = Categories.CategoryID;
                }
            }
            else if (!_settingFK)
            {
                CategoryID = null;
            }
        }

        #endregion
    }
}
