//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace Effort.Test.Data.Northwind
{
    public class NorthwindObjectContext : ObjectContext
    {
        public const string ContainerName = "NorthwindObjectContext";

        public const string DefaultConnectionStringName = "NorthwindObjectContext";

        public const string DefaultConnectionString = "name=NorthwindObjectContext";
    
        #region Constructors
    
        public NorthwindObjectContext(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public NorthwindObjectContext(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Category> Categories
        {
            get { return _categories  ?? (_categories = CreateObjectSet<Category>("Categories")); }
        }
        private ObjectSet<Category> _categories;
    
        public ObjectSet<CustomerDemography> CustomerDemographics
        {
            get { return _customerDemographics  ?? (_customerDemographics = CreateObjectSet<CustomerDemography>("CustomerDemographics")); }
        }
        private ObjectSet<CustomerDemography> _customerDemographics;
    
        public ObjectSet<Customer> Customers
        {
            get { return _customers  ?? (_customers = CreateObjectSet<Customer>("Customers")); }
        }
        private ObjectSet<Customer> _customers;
    
        public ObjectSet<Employee> Employees
        {
            get { return _employees  ?? (_employees = CreateObjectSet<Employee>("Employees")); }
        }
        private ObjectSet<Employee> _employees;
    
        public ObjectSet<OrderDetail> OrderDetails
        {
            get { return _orderDetails  ?? (_orderDetails = CreateObjectSet<OrderDetail>("OrderDetails")); }
        }
        private ObjectSet<OrderDetail> _orderDetails;
    
        public ObjectSet<Order> Orders
        {
            get { return _orders  ?? (_orders = CreateObjectSet<Order>("Orders")); }
        }
        private ObjectSet<Order> _orders;
    
        public ObjectSet<Product> Products
        {
            get { return _products  ?? (_products = CreateObjectSet<Product>("Products")); }
        }
        private ObjectSet<Product> _products;
    
        public ObjectSet<Region> Regions
        {
            get { return _regions  ?? (_regions = CreateObjectSet<Region>("Regions")); }
        }
        private ObjectSet<Region> _regions;
    
        public ObjectSet<Shipper> Shippers
        {
            get { return _shippers  ?? (_shippers = CreateObjectSet<Shipper>("Shippers")); }
        }
        private ObjectSet<Shipper> _shippers;
    
        public ObjectSet<Supplier> Suppliers
        {
            get { return _suppliers  ?? (_suppliers = CreateObjectSet<Supplier>("Suppliers")); }
        }
        private ObjectSet<Supplier> _suppliers;
    
        public ObjectSet<Territory> Territories
        {
            get { return _territories  ?? (_territories = CreateObjectSet<Territory>("Territories")); }
        }
        private ObjectSet<Territory> _territories;

        #endregion

    
    }
}
