//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;
#if !EFOLD
using System.Data.Entity.Core.EntityClient;
#else
using System.Data.EntityClient;
#endif

namespace Effort.Test.Data.Northwind
{
    public class NorthwindDbContext : DbContext
    {
        #region Constructors
    
        public NorthwindDbContext(EntityConnection connection)
            : base(connection, true)
        {
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public IDbSet<Category> Categories { get; set; }
    
        public IDbSet<CustomerDemography> CustomerDemographics { get; set; }
    
        public IDbSet<Customer> Customers { get; set; }
    
        public IDbSet<Employee> Employees { get; set; }
    
        public IDbSet<OrderDetail> OrderDetails { get; set; }
    
        public IDbSet<Order> Orders { get; set; }
    
        public IDbSet<Product> Products { get; set; }
    
        public IDbSet<Region> Regions { get; set; }
    
        public IDbSet<Shipper> Shippers { get; set; }
    
        public IDbSet<Supplier> Suppliers { get; set; }
    
        public IDbSet<Territory> Territories { get; set; }

        #endregion

    
    }
}
