//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Effort.Test.Data.Northwind
{
    
    public class Product
    {
        public virtual int ProductID { get; set; }
    
        public virtual string ProductName { get; set; }
    
        public virtual Nullable<int> SupplierID { get; set; }
    
        public virtual Nullable<int> CategoryID { get; set; }
    
        public virtual string QuantityPerUnit { get; set; }
    
        public virtual Nullable<decimal> UnitPrice { get; set; }
    
        public virtual Nullable<short> UnitsInStock { get; set; }
    
        public virtual Nullable<short> UnitsOnOrder { get; set; }
    
        public virtual Nullable<short> ReorderLevel { get; set; }
    
        public virtual bool Discontinued { get; set; }
    
        public virtual Category Category { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    
    
    }
}
