//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Effort.Test.Data.Northwind
{
    
    public class Territory
    {
        public virtual string TerritoryID { get; set; }
    
        public virtual string TerritoryDescription { get; set; }
    
        public virtual int RegionID { get; set; }
    
        public virtual Region Region { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    
    
    }
}
